In [1]:
import pandas as pd
import tensorflow as tf
import pandas as pd
import numpy as np
cars_data=pd.read_csv('./vehicles.csv')
cars_data=cars_data.drop(columns=['id','url','image_url','region_url','county','size','vin','lat','long'])
cars_data=cars_data.dropna()
cars_data=cars_data.reset_index()
cars_data=cars_data.drop(['index'],axis = 1)

In [2]:
cars_data['condition'] = cars_data['condition'].astype('category')

In [3]:
cars_data.head()

,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color,description,state
0,denver,7995,2010.0,chevrolet,silverado 1500 4wd,excellent,8 cylinders,gas,194050.0,clean,automatic,4wd,truck,white,This Silverado work truck must've been used by...,co
1,greensboro,16000,2011.0,bmw,535i,excellent,6 cylinders,gas,85000.0,salvage,automatic,fwd,sedan,grey,BMW 535i 2011 TwinPower Turbo F10 Engine: 3....,nc
2,syracuse,10950,2011.0,buick,lucerne cxl v6,excellent,6 cylinders,gas,43418.0,clean,automatic,fwd,sedan,red,"Grandma's 2011 Buick Lucerne. 43,418 babied m...",ny
3,syracuse,9400,2011.0,bmw,x5,good,6 cylinders,gas,145000.0,clean,automatic,4wd,SUV,blue,Selling a 2011 BMW X5 in mint condition with f...,ny
4,syracuse,4500,2012.0,ford,fusion sel,excellent,6 cylinders,gas,155000.0,clean,automatic,4wd,sedan,silver,For Sale 2012 Ford Fusion SEL!! This is the A...,ny

In [4]:
cars_data['condition'] = cars_data.condition.cat.codes

In [5]:
cars_data.head()

,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color,description,state
0,denver,7995,2010.0,chevrolet,silverado 1500 4wd,0,8 cylinders,gas,194050.0,clean,automatic,4wd,truck,white,This Silverado work truck must've been used by...,co
1,greensboro,16000,2011.0,bmw,535i,0,6 cylinders,gas,85000.0,salvage,automatic,fwd,sedan,grey,BMW 535i 2011 TwinPower Turbo F10 Engine: 3....,nc
2,syracuse,10950,2011.0,buick,lucerne cxl v6,0,6 cylinders,gas,43418.0,clean,automatic,fwd,sedan,red,"Grandma's 2011 Buick Lucerne. 43,418 babied m...",ny
3,syracuse,9400,2011.0,bmw,x5,2,6 cylinders,gas,145000.0,clean,automatic,4wd,SUV,blue,Selling a 2011 BMW X5 in mint condition with f...,ny
4,syracuse,4500,2012.0,ford,fusion sel,0,6 cylinders,gas,155000.0,clean,automatic,4wd,sedan,silver,For Sale 2012 Ford Fusion SEL!! This is the A...,ny

In [6]:
target = cars_data.pop('condition')

In [7]:
cars_data.head()

,region,price,year,manufacturer,model,cylinders,fuel,odometer,title_status,transmission,drive,type,paint_color,description,state
0,denver,7995,2010.0,chevrolet,silverado 1500 4wd,8 cylinders,gas,194050.0,clean,automatic,4wd,truck,white,This Silverado work truck must've been used by...,co
1,greensboro,16000,2011.0,bmw,535i,6 cylinders,gas,85000.0,salvage,automatic,fwd,sedan,grey,BMW 535i 2011 TwinPower Turbo F10 Engine: 3....,nc
2,syracuse,10950,2011.0,buick,lucerne cxl v6,6 cylinders,gas,43418.0,clean,automatic,fwd,sedan,red,"Grandma's 2011 Buick Lucerne. 43,418 babied m...",ny
3,syracuse,9400,2011.0,bmw,x5,6 cylinders,gas,145000.0,clean,automatic,4wd,SUV,blue,Selling a 2011 BMW X5 in mint condition with f...,ny
4,syracuse,4500,2012.0,ford,fusion sel,6 cylinders,gas,155000.0,clean,automatic,4wd,sedan,silver,For Sale 2012 Ford Fusion SEL!! This is the A...,ny

In [9]:
cars_learn_data=cars_data['description']

In [12]:
import nltk
from nltk.corpus import movie_reviews
import random

In [14]:
dataset = tf.data.Dataset.from_tensor_slices((cars_data['price'], target.values))

In [15]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: 7995, Target: 0
Features: 16000, Target: 0
Features: 10950, Target: 0
Features: 9400, Target: 2
Features: 4500, Target: 0

In [16]:
train_dataset = dataset.shuffle(len(cars_data)).batch(1)

In [17]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [18]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15
146101/146101 [==============================] - 284s 2ms/step - loss: 12686792.0000 - accuracy: 0.0283
Epoch 2/15
146101/146101 [==============================] - 279s 2ms/step - loss: 2424726528.0000 - accuracy: 0.0281
Epoch 3/15
146101/146101 [==============================] - 290s 2ms/step - loss: 8507823616.0000 - accuracy: 0.0281
Epoch 4/15
132140/146101 [==========================>...] - ETA: 26s - loss: 23119230976.0000 - accuracy: 0.0283

KeyboardInterrupt: